name             'was'
maintainer       'IBM Corp'
maintainer_email ''
license 'Copyright IBM Corp. 2016, 2017'
description      'Installs and configures WebSphere Application Server and WebSphere Application Server Network Deployment'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))

version '1.0.2'

depends          'ibm_cloud_utils'
depends          'im'
depends          'linux'
supports 'RHEL6', '>= 6.5'
supports 'RHEL7', '>= 7.0'
supports 'Ubuntu14', '>= 14.04'
supports 'Ubuntu16', '>= 16.0.4' 
attribute 'was/config/enable_admin_security',
          :choice => ['true', 'false'],
          :default => 'true',
          :description => 'Enable WebSphere administrative console security',
          :displayname => 'WebSphere enable administrative security',
          :hidden => 'true',
          :options => ['true', 'false'],
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/config/os_service',
          :choice => ['true', 'false'],
          :default => 'true',
          :description => 'Setup appropriate operating system job to start WebSphere at system startup',
          :displayname => 'WebSphere enable automatic start of servers',
          :hidden => 'true',
          :options => ['true', 'false'],
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/config/use_default_certs',
          :choice => ['true', 'false'],
          :default => 'true',
          :description => 'Use WebSphere default certificates when creating profiles',
          :displayname => 'WebSphere create a new default personal certificate',
          :hidden => 'true',
          :options => ['true', 'false'],
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/dmgr_host_name',
          :default => '',
          :description => 'The fully qualified domain name of the deployment manager to federate this node to',
          :displayname => 'WebSphere Deployment Manager hostname',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/dmgr_role_name',
          :default => '',
          :description => 'Used for Chef search',
          :displayname => 'dmgr_role_name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/base',
          :default => 'false',
          :description => 'WebSphere Application Server will be installed and configured',
          :displayname => 'WebSphere Base Edition',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/edition/nd',
          :default => 'true',
          :description => 'WebSphere Application Server Network Deployment will be installed and configured',
          :displayname => 'WebSphere ND Edition',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/core.feature',
          :default => 'true',
          :description => 'Indicates that the application server feature (core.feature) should be installed',
          :displayname => 'WebSphere install runtime',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/features/ejbdeploy',
          :default => 'true',
          :description => 'Indicates whether the optional feature EJBDeploy tool for pre-EJB 3.0 modules should be installed',
          :displayname => 'WebSphere install optional EJBDeploy feature',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/embeddablecontainer',
          :default => 'true',
          :description => 'Indicates whether the embeddable EJB container should be installed',
          :displayname => 'WebSphere install optional Embeddable EJB Container feature',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/liberty',
          :default => 'false',
          :description => 'Indicates whether the WebSphere Liberty Application Server should be installed. Used for WebSphere installations that bundled Liberty as an install option',
          :displayname => 'WebSphere features liberty',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/samples',
          :default => 'false',
          :description => 'Indicates whether the PlantsByWebSphere sample application should be installed',
          :displayname => 'WebSphere install optional WebSphere Sample applications',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/features/thinclient',
          :default => 'true',
          :description => 'Indicates whether the optional IBM stand-alone thin clients and resource adapters should be installed',
          :displayname => 'WebSphere install optional stand-alone thin clients and resource adapters',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/ihs_host_name',
          :default => '',
          :description => 'Fully qualified domain name of the IBM HTTP server',
          :displayname => 'IBM HTTP hostname',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/ihs_role_names',
          :default => '',
          :description => 'Used for Chef search',
          :displayname => 'ihs_role_names',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'array'
attribute 'was/install_dir',
          :default => '/opt/IBM/WebSphere/AppServer',
          :description => 'The installation root directory for the WebSphere Application Server product binaries',
          :displayname => 'WebSphere product installation directory',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/enable',
          :choice => ['true', 'false'],
          :default => 'true',
          :description => 'Installation Manager response file option to install Java 8 SDK. Valid only for WebSphere V9',
          :displayname => 'WebSphere install Java 8 SDK',
          :hidden => 'true',
          :options => ['true', 'false'],
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/java_features/websphere_java_v8/offering_id',
          :default => 'com.ibm.java.jdk.v8',
          :description => 'Java SDK installation manager offering ID value',
          :displayname => 'WebSphere Java 8 SDK installation manager offering id',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'was/java_version',
          :default => '8.0.4.70',
          :description => 'The Java SDK version that should be installed with the WebSphere Application Server. Example format is 8.0.4.70',
          :displayname => 'WebSphere Java SDK version',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_perms',
          :default => '750',
          :description => 'File permissions for the WebSphere installation',
          :displayname => 'WebSphere operating system permissions',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/comment',
          :default => 'WAS administrative user',
          :description => 'Comment that will be added when creating the userid',
          :displayname => 'WebSphere user comment for user',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/gid',
          :default => 'wasgrp',
          :description => 'Operating system group name that will be assigned to the product installation',
          :displayname => 'WebSphere user group name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/home',
          :default => '/home/wasadmin',
          :description => 'Home directory location for operating system user that is used for product installation',
          :displayname => 'WebSphere installation userid home directory',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/ldap_user',
          :choice => ['true', 'false'],
          :default => 'false',
          :description => 'A flag which indicates whether to create the WebSphere user locally, or utilize an LDAP based user',
          :displayname => 'WebSphere to use LDAP for authentication',
          :hidden => 'true',
          :options => ['true', 'false'],
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/name',
          :default => 'wasadmin',
          :description => 'Operating system userid that will be used to install the product. Userid will be created if it does not exist',
          :displayname => 'WebSphere installation userid',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/os_users/was/shell',
          :default => '/bin/bash',
          :description => 'Default shell for the operating system userid',
          :displayname => 'WebSphere userid default shell',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profile_dir',
          :default => '/opt/IBM/WebSphere/AppServer/profiles',
          :description => 'The directory path that contains WebSphere Application Server profiles',
          :displayname => 'WebSphere profile location',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/cell',
          :default => 'cell01',
          :description => 'A cell name is a logical name for the group of nodes administered by the deployment manager cell',
          :displayname => 'WebSphere cell name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/host',
          :default => '',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'WebSphere Deployment Manager host name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on keystore created during profile creation',
          :displayname => 'WebSphere default keystore password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/node',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'A node name is for administration by the deployment manager.  The name must be unique within the cell',
          :displayname => 'WebSphere node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'WebSphere personal certificate Distingushed name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'WebSphere personal certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/BOOTSTRAP_ADDRESS',
          :default => '9809',
          :description => 'Deployment Manager Bootstrap Port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'WebSphere Bootstrap Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CELL_DISCOVERY_ADDRESS',
          :default => '7277',
          :description => 'Deployment Manager Cell Discovery Address port value (CELL_DISCOVERY_ADDRESS)',
          :displayname => 'WebSphere Cell Discovery Address',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'Deployment Manager CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'WebSphere CSIV2 Client Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'Deployment Manager CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS) value',
          :displayname => 'WebSphere CSIV2 Server Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DCS_UNICAST_ADDRESS',
          :default => '9352',
          :description => 'Deployment Manager High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'WebSphere High Availability Manager Communication Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/DataPowerMgr_inbound_secure',
          :default => '5555',
          :description => 'Deployment Manager DataPower Appliance Manager Secure Inbound Port (DataPowerMgr_inbound_secure)',
          :displayname => 'WebSphere DataPower Appliance Manager Secure Inbound Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9632',
          :description => 'Deployment Manager IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere IPC Connector Port value',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'Deployment Manager ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'WebSphere ORB Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11006',
          :description => 'Deployment Manager Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Administration Overlay TCP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11005',
          :description => 'Deployment Manager Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Administration Overlay UDP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'Deployment Manager SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'WebSphere SAS_SSL_SERVERAUTH_LISTENER_ADDRESS Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8879',
          :description => 'Deployment Manager SOAP Connector Port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere SOAP Connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'Deployment Manager Status Update Listener Port (STATUS_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Status Update Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost',
          :default => '9060',
          :description => 'Deployment Manager Administrative Console Port (WC_adminhost)',
          :displayname => 'WebSphere Administrative Console Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'Deployment Manager Adminsitrative Secure Console Port (WC_adminhost_secure)',
          :displayname => 'WebSphere Administrative Console Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/ports/XDAGENT_PORT',
          :default => '7060',
          :description => 'Deployment Manager Middleware Agent RPC Port (XDAGENT_PORT)',
          :displayname => 'WebSphere Middleware Agent RPC Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/profile',
          :default => 'Dmgr01',
          :description => 'WebSphere Deployment Manager profile name',
          :displayname => 'WebSphere Deployment Manager profile name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'WebSphere root certificate distinguished name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/dmgr/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'WebSphere root signing certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/cell',
          :default => 'cell01',
          :description => 'Cell name of the Job manager ',
          :displayname => 'WebSphere Job Manager cell name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/host',
          :default => '{FULLHOSTNAME}',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'WebSphere Job Manager host name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'WebSphere default keystore password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/node',
          :default => '{SHORTHOSTNAME}JobMgr01',
          :description => 'Node name is for administration and must be unique',
          :displayname => 'WebSphere Job Manager node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'WebSphere personal certificate distingushed name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'WebSphere personal certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/BOOTSTRAP_ADDRESS',
          :default => '9808',
          :description => 'Bootstrap Port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'WebSphere Job Manager Bootstrap address',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_ SSL_ MUTUALAUTH_ LISTENER_ ADDRESS)	9402',
          :displayname => 'WebSphere Job Manager CSIV2 Client Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_ SSL_ SERVERAUTH_ LISTENER_ ADDRESS)',
          :displayname => 'WebSphere Job Manager CSIV2 Server Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/IPC_CONNECTOR_ADDRESS',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS),
# <md>          :type => ',
          :displayname => 'WebSphere Job Manager IPC Connector Port value'
attribute 'was/profiles/job_manager/ports/ORB_LISTENER_ADDRESS',
          :default => '9099',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Job Manager ORB listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'SAS_ SSL_ SERVERAUTH_ LISTENER_ ADDRESS (Deprecated)',
          :displayname => 'WebSphere Job Manager SAS SSL ServerAuth Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8876',
          :description => 'SOAP Connector Port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere Job Manager SOAP Connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/STATUS_LISTENER_ADDRESS',
          :default => '9425',
          :description => 'Status Update Listener Port (STATUS_ LISTENER_ ADDRESS)',
          :displayname => 'WebSphere Job Manager Status update listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost',
          :default => '9960',
          :description => 'Job Manager Administrative Console Port (WC_adminhost)',
          :displayname => 'WebSphere Administrative Console Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/ports/WC_adminhost_secure',
          :default => '9943',
          :description => 'Job Manager Adminsitrative Secure Console Port (WC_adminhost_secure)',
          :displayname => 'WebSphere Administrative Console Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/profile',
          :default => 'JobMgr01',
          :description => 'Job Manager profile name',
          :displayname => 'WebSphere Job Manager profile name ',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'WebSphere root certificate distinguished name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/job_manager/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'WebSphere root signing certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_host',
          :default => '',
          :description => 'Speicfy the host name or IP address for an existing deployment manager',
          :displayname => 'WebSphere Deployment Manager host name or IP address',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/dmgr_port',
          :default => '',
          :description => 'Deployment Manager SOAP Port that is used when federating the custom profile',
          :displayname => 'WebSphere Deployment Manager SOAP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/host',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_),
# <md>          :type => ',
          :displayname => 'WebSphere custom profile host name'
attribute 'was/profiles/node_profile/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'WebSphere default keystore password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'Unique node name for this federated node.  Must be unique within the cell',
          :displayname => 'WebSphere custom profile node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'WebSphere personal certificate distingushed name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'WebSphere personal certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/BOOTSTRAP_ADDRESS',
          :default => '2810',
          :description => 'Server bootstrap (BOOTSTRAP_ADDRESS)',
          :displayname => 'WebSphere Bootstrap Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9202',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'WebSphere CSIV2 Client Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9201',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS)',
          :displayname => 'WebSphere CSIV2 Server Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/DCS_UNICAST_ADDRESS',
          :default => '9354',
          :description => 'High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'WebSphere High Availability Manager Communication Port (DCS)',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9626',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere IPC Connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_DISCOVERY_ADDRESS',
          :default => '7272',
          :description => 'Node Discovery Address (NODE_DISCOVERY_ADDRESS)',
          :displayname => 'WebSphere Node Discovery Address',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5001',
          :description => 'Node IPV6 Discovery Address (NODE_IPV6_MULTICAST_DISCOVERY_ADDRESS)',
          :displayname => 'WebSphere Node IPV6 Discovery Address Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/NODE_MULTICAST_DISCOVERY_ADDRESS',
          :default => '5000',
          :description => 'was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :displayname => 'WebSphere was node_profile profiles ports NODE_MULTICAST_DISCOVERY_ADDRESS',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/ORB_LISTENER_ADDRESS',
          :default => '9101',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'WebSphere ORB Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11002',
          :description => 'Node Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Node Administration Overlay TCP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11001',
          :description => 'Node Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Node Administration Overlay UDP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9901',
          :description => 'was node_profile profiles ports SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'WebSphere SAS_SSL_SERVERAUTH_LISTENER_ADDRESS Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8878',
          :description => 'SOAP Connector Port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere SOAP Connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/STATUS_LISTENER_ADDRESS',
          :default => '9420',
          :description => 'Status Update Listener Port (STATUS_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Status Update Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/WC_adminhost',
          :default => '9060',
          :description => 'Administrative Console Port (WC_adminhost)',
          :displayname => 'WebSphere Administrative Console Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/ports/XDAGENT_PORT',
          :default => '7061',
          :description => 'Node Middleware Agent RPC Port (XDAGENT_PORT)',
          :displayname => 'WebSphere Node Middleware Agent RPC Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/profile',
          :default => 'Custom01',
          :description => 'Profile name for a custom profile',
          :displayname => 'WebSphere Custom Node profile name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'WebSphere root certificate distinguished name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/node_profile/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'WebSphere root signing certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/cell',
          :default => 'cell01',
          :description => 'Cell name for the application server',
          :displayname => 'WebSphere Application Server cell name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/host',
          :default => '{FULLHOSTNAME}',
          :description => 'A host name is the domain name system (DNS) name (short or long) or the IP address of this virtual machine and cannot contain an understore (_)',
          :displayname => 'WebSphere Application Server host name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/keystorepassword',
          :default => '',
          :description => 'Specifies the password to use on all keystore files created during profile creation',
          :displayname => 'WebSphere default keystore password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/node',
          :default => '{SHORTHOSTNAME}Node01',
          :description => 'A node name is used for administration',
          :displayname => 'WebSphere Application Server node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the personal certificate that you are creating when you create the profile',
          :displayname => 'WebSphere personal certificate distingushed name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/personalcertvalidityperiod',
          :default => '3',
          :description => 'An optional parameter that specifies the amount of time in years that the default personal certificate is valid',
          :displayname => 'WebSphere personal certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/BOOTSTRAP_ADDRESS',
          :default => '2809',
          :description => 'Bootstrap Port value (BOOTSTRAP_ADDRESS)',
          :displayname => 'WebSphere Application Server bootstrap address',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS',
          :default => '9402',
          :description => 'CSIV2 Client Authentication Listener Port (CSIV2_SSL_MUTUALAUTH_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Application server CSIV2 Client Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9403',
          :description => 'CSIV2 Server Authentication Listener Port (CSIV2_SSL_SERVERAUTH_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Application Server CSIV2 Server Authentication Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/DCS_UNICAST_ADDRESS',
          :default => '9353',
          :description => 'High Availability Manager Communication Port (DCS_UNICAST_ADDRESS)',
          :displayname => 'WebSphere Application Server High Availability Manager Communication Port ',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/IPC_CONNECTOR_ADDRESS',
          :default => '9633',
          :description => 'IPC Connector Port value (IPC_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere Application Server IPC Connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/ORB_LISTENER_ADDRESS',
          :default => '9100',
          :description => 'ORB Listener Port (ORB_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Application Server ORB Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_TCP_LISTENER_ADDRESS',
          :default => '11004',
          :description => 'Administration Overlay TCP Port (OVERLAY_TCP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Application Server Administration Overlay TCP Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/OVERLAY_UDP_LISTENER_ADDRESS',
          :default => '11003',
          :description => 'Administration Overlay UDP Port (OVERLAY_UDP_LISTENER_ADDRESS)',
          :displayname => 'WebSphere Application Server Administration Overlay UDP Port ',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :default => '9401',
          :description => 'Application Server SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :displayname => 'WebSphere Application Server SAS_SSL_SERVERAUTH_LISTENER_ADDRESS',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_ADDRESS',
          :default => '7276',
          :description => 'Service Integration Port (SIB_ENDPOINT_ADDRESS)',
          :displayname => 'WebSphere Application Server Service Integration Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_ENDPOINT_SECURE_ADDRESS',
          :default => '7286',
          :description => 'Service Integration Secure Port  (SIB_ENDPOINT_SECURE_ADDRESS)',
          :displayname => 'WebSphere Application Server Service Integration Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_ADDRESS',
          :default => '5558',
          :description => 'MQ Transport Port (SIB_MQ_ENDPOINT_ADDRESS)',
          :displayname => 'WebSphere Application Server MQ Transport Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIB_MQ_ENDPOINT_SECURE_ADDRESS',
          :default => '5578',
          :description => 'MQ Transport Secure Port  (SIB_MQ_ENDPOINT_SECURE_ADDRESS)',
          :displayname => 'WebSphere Application Server MQ Transport Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST',
          :default => '5060',
          :description => 'SIP Container Port (SIP_DEFAULTHOST)',
          :displayname => 'WebSphere Application Server SIP Container Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SIP_DEFAULTHOST_SECURE',
          :default => '5061',
          :description => 'SIP Container Secure Port (SIP_DEFAULTHOST_SECURE)',
          :displayname => 'WebSphere Application Server SIP Container Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/SOAP_CONNECTOR_ADDRESS',
          :default => '8880',
          :description => 'SOAP Connector Port value (SOAP_CONNECTOR_ADDRESS)',
          :displayname => 'WebSphere Application Server SOAP connector Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost',
          :default => '9060',
          :description => 'Server Administrative Console Port (WC_adminhost)',
          :displayname => 'WebSphere Administrative Console Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_adminhost_secure',
          :default => '9043',
          :description => 'Server Adminsitrative Secure Console Port (WC_adminhost_secure)',
          :displayname => 'WebSphere Administrative Console Secure Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost',
          :default => '9080',
          :description => 'HTTP Transport Port (WC_defaulthost)',
          :displayname => 'WebSphere Application Server HTTP Transport Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/ports/WC_defaulthost_secure',
          :default => '9443',
          :description => 'HTTP Transport Secure Port (WC_defaulthost_secure)',
          :displayname => 'WebSphere Application Server Secure HTTP Transport Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/profile',
          :default => 'AppSrv01',
          :description => 'Application server profile name',
          :displayname => 'WebSphere Application Server profile name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/server',
          :default => 'server1',
          :description => 'Name of the application server',
          :displayname => 'WebSphere Application Server name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertdn',
          :default => '',
          :description => 'Specifies the distinguished name of the root signing certificate that you create when you create the profile',
          :displayname => 'WebSphere root certificate distinguished name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/profiles/standalone_profiles/standalone1/signingcertvalidityperiod',
          :default => '15',
          :description => 'An optional parameter that specifies the amount of time in years that the root signing certificate is valid',
          :displayname => 'WebSphere root signing certificate expiration period in years',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/security/admin_user',
          :default => 'wasadmin',
          :description => 'The username for securing the WebSphere adminstrative console',
          :displayname => 'WebSphere administrative user name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/security/admin_user_pwd',
          :default => '',
          :description => 'The password for the WebSphere administrative account',
          :displayname => 'WebSphere administrative user password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/host_name',
          :default => '',
          :description => 'The host name or ipaddress of the unmanaged host',
          :displayname => 'WebSphere Unmanaged host name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'Node name for the unmanaged node',
          :displayname => 'WebSphere Unmanaged node name ',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/unmanaged_node/unmngNode01/os',
          :default => 'linux',
          :description => 'Indicates the operating system type for the unmanaged node',
          :displayname => 'WebSphere Unmanaged node operating system type',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/version',
          :default => '9.0.0.4',
          :description => 'The release and fixpack level of WebSphere Application Server to be installed. Example formats are 8.5.5.12 or 9.0.0.4',
          :displayname => 'WebSphere Application Server Version',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/admin_port',
          :default => '8008',
          :description => 'IBM HTTP Administrative Server Port.  Used for creating the web server definition',
          :displayname => 'IBM HTTP Administrative Server Port',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_password',
          :default => '',
          :description => 'IBM HTTP administrative username password. Used for creating the web server definition ',
          :displayname => 'IBM HTTP administrative username password',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'true',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/ihs_admin_user',
          :default => 'ihsadmin',
          :description => 'IBM HTTP administrative username. Used for creating the web server definition',
          :displayname => 'IBM HTTP administrative username',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/install_dir',
          :default => '/opt/IBM/HTTPServer',
          :description => 'Specify the HTTP Server installation directory. Used for creating the web server definition',
          :displayname => 'IBM HTTP Server installation directory',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/node_name',
          :default => '{SHORTHOSTNAME}UnmangedNode01',
          :description => 'Web server node name',
          :displayname => 'WebSphere was webserver ihs_server node_name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/plugin_dir',
          :default => '/opt/IBM/WebSphere/Plugins',
          :description => 'Specify the webserver plugin directory. Used for creating the web server definition',
          :displayname => 'WebSphere plugin installation directory',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webapp_mapping',
          :default => 'ALL',
          :description => 'Indicate how the applications should be mapped from the webserver',
          :displayname => 'Map all applications to the webserver',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_name',
          :default => 'webserver1',
          :description => 'Web server server name',
          :displayname => 'WebSphere was webserver ihs_server webserver_name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_port',
          :default => '80',
          :description => 'IBM HTTP Server Listener Port that will receive requests on. Use for creating the web server definition',
          :displayname => 'IBM HTTP Server Listener Port',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/webserver/ihs_server/webserver_type',
          :default => 'IHS',
          :description => 'HTTP Server vendor.  Example IHS',
          :displayname => 'Type of WebServer',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_name',
          :default => 'cluster01',
          :description => 'Name of the cluster that will be created',
          :displayname => 'WebSphere Cluster name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/cluster_servers/cluster_server01/server_name',
          :default => 'server1',
          :description => 'Name of the cluster member that will created on each of the nodes',
          :displayname => 'WebSphere Cluster member name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/clusters/cluster01/session_rep',
          :default => 'true ',
          :description => 'was wsadmin clusters cluster01 session_rep',
          :displayname => 'was wsadmin clusters cluster01 session_rep',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/node_name',
          :default => '{SHORTHOSTNAME}CellManager01',
          :description => 'Node for the deployment manager that will be updated',
          :displayname => 'WebSphere Deployment Manager node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/profile_path',
          :default => '',
          :description => 'Directoy where the deployment manager profile resides',
          :displayname => 'WebSphere Deployment Manager profile path',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'WebSphere Deployment Manager minimum JVM Heap Size',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'WebSphere Deployment Manager maximum JVM Heap Size',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/dmgr/jvmproperty/server_name',
          :default => 'dmgr',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'WebSphere Deployment Manager server name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/node_name',
          :default => '',
          :description => 'Node for the node agent that will be updated',
          :displayname => 'WebSphere Node Agent node name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/profile_path',
          :default => '',
          :description => 'Node Agent directory where the profile resides',
          :displayname => 'WebSphere Node Agent profile path',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'WebSphere Node Agent minimum JVM Heap Size',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'WebSphere Node Agent maximum JVM heap size',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/nodeagent/jvmproperty/server_name',
          :default => 'nodeagent',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'WebSphere Node Agent server name',
          :hidden => 'true',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/node_name',
          :default => '',
          :description => 'Node for the application server that will be updated',
          :displayname => 'WebSphere Application Server node name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/profile_path',
          :default => '',
          :description => 'Directoy where the application server profile resides',
          :displayname => 'WebSphere Application Server profile path',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_initial',
          :default => '256',
          :description => 'Minimum JVM heap size',
          :displayname => 'WebSphere Application Server minimum JVM Heap Size',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/property_value_maximum',
          :default => '512',
          :description => 'Maximum JVM heap size',
          :displayname => 'WebSphere Application Server maximum JVM Heap Size',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
attribute 'was/wsadmin/standalone/jvmproperty/server_name',
          :default => '',
          :description => 'Name of server that will be updated for JVM heap size',
          :displayname => 'WebSphere Application Server name',
          :hidden => 'false',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'true',
          :type => 'string'
recipe 'was::cleanup.rb', '
Cleanup Post WebSphere Install
'
recipe 'was::configure_dmgr.rb', '
Configure Deployment Manager JVM min and max HeapSize.
'
recipe 'was::configure_nodeagent.rb', '
Configure Node agent JVM min and max HeapSize settings
'
recipe 'was::configure_standalone.rb', '
Configure Websphere standalone server JVM min and max HeapSize.
'
recipe 'was::create_cluster.rb', '
Creates a WebSphere cluster for a given cell.  There is no retry logic if system management throws an exception.
'
recipe 'was::create_clustermember.rb', '
Create Websphere cluster members/servers
'
recipe 'was::create_dmgr.rb', '
Creates WebSphere Deployment Manager profile and starts the deployment manager.
'
recipe 'was::create_job_manager.rb', '
Create WebSphere Job Manager profile and starts the job manager.
'
recipe 'was::create_managed.rb', '
Create node agent, manage node profile, start the node agent
'
recipe 'was::create_standalone.rb', '
Create Websphere standalone server profile and starts the server.
'
recipe 'was::gather_evidence.rb', '
Gather evidence that installation was successful
'
recipe 'was::install.rb', '
Installs WebSphere Application Server V8.5.5 or V9
'
recipe 'was::prereq.rb', '
This recipe will add to the environment the necessary Pre-Requisites to be added prior ro WebSphere Instalation, this will include
Adding users, Packages, Kernel Configuration
'
recipe 'was::prereq_check.rb', '
This recipe will check the environment prior to installing software.
'
recipe 'was::start_clustermember.rb', '
Start the Websphere cluster members/application servers
'
recipe 'was::unmanaged_webserver.rb', '
Creates a IBM HTTP webserver server defintion as an unmanaged node.
'
